[project]
name = "central"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.5",
    "django-htmx>=1.23.2",
    "django-tailwind[reload]>=4.2.0",
    "django-unfold>=0.63.0",
]
