# Generated by Django 5.2.4 on 2025-08-08 04:12

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteractivePointField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Use map widget to point the location', srid=4326)),
                ('location_has_default', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-104.9903, 39.7392), srid=4326)),
                ('location_optional', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Interactive PointField Widget',
                'verbose_name_plural': 'Interactive PointField Widget',
            },
        ),
        migrations.CreateModel(
            name='InteractiveInlinePointField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_point', django.contrib.gis.db.models.fields.PointField(help_text='Use map widget to point the location', srid=4326)),
                ('second_point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-104.9903, 39.7392), srid=4326)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.interactivepointfield')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaticPointField',
            fields=[
            ],
            options={
                'verbose_name': 'Static PointField Widget',
                'verbose_name_plural': 'Static PointField Widget',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.interactivepointfield',),
        ),
    ]
